python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/VESPA_1.0/testing.txt"
# python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPI.B.1.3-210.txt"
python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPI.F.1.1.txt"
python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPI.F.1.2.txt"
python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPI.F.1.3.txt"
python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPI.F.1.4.txt"
python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPI.F.1.5.txt"
python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPI.F.1.6.txt"
python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPI.F.2.1.txt"
python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPI.F.2.2.txt"
python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPI.F.2.3.txt"
python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPI.F.2.4.txt"
python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPI.F.2.5.txt"
# python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPT.B.2.4-210.txt"
# python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPT.F.1.7.txt"
# python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPT.F.2.1.txt"
# python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPT.F.2.2.txt"
# python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPT.F.2.3.txt"
# python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPT.F.2.4.txt"
# python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPT.F.2.5.txt"
# python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPT.F.2.6.txt"
# python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPT.F.2.7.txt"
# python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPT.F.4.5.txt"
# python3 test.py --config_file ./configs/vespa.yaml --num_workers 8 --weight_file './outputs/final.pth' --test_file "./data/vespa/estec_bop/TestPT.F.4.6.txt"
