MODEL:
  # BACKBONE: 'darknet_tiny'
  BACKBONE: 'darknet53'
  ANCHOR_SIZES: [32, 64, 128, 256, 512]
  ANCHOR_STRIDES: [8, 16, 32, 64, 128]
DATASETS:
  TRAIN: './data/Occ-LINEMOD/train_pbr.txt'
  VALID: './data/linemod/linemod_subset_test_all.txt'
  TEST: './data/linemod/linemod_subset_test_all.txt'
  MESH_DIR: './data/linemod/models_subset/'
  BBOX_FILE: './data/linemod/linemod_subset_bbox.json'
  MESH_DIAMETERS: [104.26,250.85,177.43,204.83,154.63,264.12,110.83,164.65,178.35,145.61,279.04,287.24,213.25]
  SYMMETRY_TYPES: { # class IDs start from 0
    "cls_7":['X',180,'Y',180,'Z',180], 
    "cls_8":['Z',180]
  }
  N_CLASS: 14
INPUT:
  INTERNAL_WIDTH: 640
  INTERNAL_HEIGHT: 480
  INTERNAL_K: [572.4114, 0, 325.2611, 0, 573.57043, 242.04899, 0, 0, 1]
SOLVER:
  IMS_PER_BATCH: 16
  # 
  BASE_LR: 0.001
  MAX_ITER: 200000
  # 
  LOSS_WEIGHT_CLS: 0.1
  # LOSS_WEIGHT_REG: 0.01
  # LOSS_REG_TYPE: '2D'
  LOSS_WEIGHT_REG: 1
  LOSS_REG_TYPE: '3D'
  POSITIVE_TYPE: 'SSC'
  POSITIVE_LAMBDA: 1.0
  REGRESSION_TYPE: 'POINT'
  AUGMENTATION_SHIFT: 0.1
  AUGMENTATION_SCALE: 0.1
  AUGMENTATION_ROTATION: 45
  AUGMENTATION_ColorH: 0.2
  AUGMENTATION_ColorS: 0.5
  AUGMENTATION_ColorV: 0.5
  AUGMENTATION_Sharpen: 0
  AUGMENTATION_Smooth: 5
  AUGMENTATION_Noise: 0.1
  #AUGMENTATION_ColorH: 0.2
  #AUGMENTATION_ColorS: 0.5
  #AUGMENTATION_ColorV: 0.5
  #AUGMENTATION_Noise: 0.1
  #AUGMENTATION_Smooth: 2.0
  #AUGMENTATION_OCCLUSION: 0.8
  # AUGMENTATION_BACKGROUND_DIR: './data/SUN2012pascalformat/JPEGImages/'
TEST:
  IMS_PER_BATCH: 8
  CONFIDENCE_TH: 0.1
