MODEL:
  BACKBONE: 'darknet53'
  ANCHOR_SIZES: [32, 64, 128, 256, 512]
  ANCHOR_STRIDES: [8, 16, 32, 64, 128]
DATASETS:
  TRAIN: './data/SwissCube_1.0/training.txt'
  VALID: './data/SwissCube_1.0/validation.txt'
  TEST: './data/SwissCube_1.0/testing.txt'
  MESH_DIR: './data/SwissCube_1.0/models/'
  BBOX_FILE: './data/SwissCube_1.0/swisscube_bbox.json'
  MESH_DIAMETERS: [178.46]
  N_CLASS: 2
INPUT:
  INTERNAL_WIDTH: 512
  INTERNAL_HEIGHT: 512
  INTERNAL_K: [303.7865161198519, 0, 256, 0, 303.7865161198519, 256, 0, 0, 1]
SOLVER:
  IMS_PER_BATCH: 16
  # 
  BASE_LR: 0.001
  MAX_ITER: 200000
  # 
  LOSS_WEIGHT_CLS: 0.1
  # LOSS_WEIGHT_REG: 0.01
  # LOSS_REG_TYPE: '2D'
  LOSS_WEIGHT_REG: 1
  LOSS_REG_TYPE: '3D'
  POSITIVE_TYPE: 'SSC'
  POSITIVE_LAMBDA: 1.0
  REGRESSION_TYPE: 'POINT'
  AUGMENTATION_SHIFT: 0.1
  AUGMENTATION_SCALE: 0.1
  AUGMENTATION_ROTATION: 45
  AUGMENTATION_ColorH: 0.2
  AUGMENTATION_ColorS: 0.5
  AUGMENTATION_ColorV: 0.5
  AUGMENTATION_Sharpen: 0
  AUGMENTATION_Smooth: 5
  AUGMENTATION_Noise: 0.1
  #AUGMENTATION_ColorH: 0.2
  #AUGMENTATION_ColorS: 0.5
  #AUGMENTATION_ColorV: 0.5
  #AUGMENTATION_Noise: 0.05
  #AUGMENTATION_Smooth: 1.0
  # AUGMENTATION_OCCLUSION: 0.5
  # AUGMENTATION_BACKGROUND_DIR: './data/SUN2012pascalformat/JPEGImages/'
TEST:
  IMS_PER_BATCH: 8
  CONFIDENCE_TH: 0.1
