MODEL:
  # BACKBONE: 'darknet_tiny'
  BACKBONE: 'darknet53'
  ANCHOR_SIZES: [32, 64, 128, 256, 512]
  ANCHOR_STRIDES: [8, 16, 32, 64, 128]
DATASETS:
  TRAIN: './data/ycbv/train_pbr.txt'
  #TRAIN: './data/ycbv/train_pyrender.txt'
  #TRAIN: './data/ycbv/train_real.txt'
  #TRAIN: './data/ycbv/train_pbr_real.txt'
  VALID: './data/ycbv/test.txt'
  TEST: './data/ycbv/test.txt'
  MESH_DIR: './data/ycbv/models_vc/'
  BBOX_FILE: './data/ycbv/ycbv_bbox.json'
  MESH_DIAMETERS: [
    172.16,269.58,198.38,
    120.66,199.79,90.17,
    142.58,114.39,129.73,
    198.40,263.60,260.76,
    162.27,126.86,230.44,
    237.30,204.11,121.46,
    183.08,231.39,102.92
    ]
  SYMMETRY_TYPES: { # class IDs start from 0
    "cls_12":['Z',0], 
    "cls_15":['X',180,'Y',180,'Z',90], 
    "cls_18":['Y',180], 
    "cls_19":['X',180], 
    "cls_20":['X',180,'Y',90,'Z',180]
    }
  N_CLASS: 22
INPUT:
  INTERNAL_WIDTH: 640
  INTERNAL_HEIGHT: 480
  INTERNAL_K: [1066.778, 0.0, 312.9869, 0.0, 1067.487, 241.3109, 0.0, 0.0, 1.0]
  # INTERNAL_WIDTH: 960
  # INTERNAL_HEIGHT: 720
  # INTERNAL_K: [1600.167, 0.0, 469.48035, 0.0, 1601.2305, 361.96635, 0.0, 0.0, 1.0]
SOLVER:
  IMS_PER_BATCH: 16
  # 
  BASE_LR: 0.001
  MAX_ITER: 200000
  # 
  LOSS_WEIGHT_CLS: 0.1
  # LOSS_WEIGHT_REG: 0.01
  # LOSS_REG_TYPE: '2D'
  LOSS_WEIGHT_REG: 1
  LOSS_REG_TYPE: '3D'
  POSITIVE_TYPE: 'SSC'
  POSITIVE_LAMBDA: 1.0
  REGRESSION_TYPE: 'POINT'
  AUGMENTATION_SHIFT: 0.1
  AUGMENTATION_SCALE: 0.1
  AUGMENTATION_ROTATION: 45
  AUGMENTATION_ColorH: 0.2
  AUGMENTATION_ColorS: 0.5
  AUGMENTATION_ColorV: 0.5
  AUGMENTATION_Sharpen: 0
  AUGMENTATION_Smooth: 5
  AUGMENTATION_Noise: 0.1
  #AUGMENTATION_ColorH: 0.2
  #AUGMENTATION_ColorS: 0.5
  #AUGMENTATION_ColorV: 0.5
  #AUGMENTATION_Noise: 0.1
  #AUGMENTATION_Smooth: 2.0
  #AUGMENTATION_OCCLUSION: 0.8
  # AUGMENTATION_BACKGROUND_DIR: './data/SUN2012pascalformat/JPEGImages/'
TEST:
  IMS_PER_BATCH: 8
  CONFIDENCE_TH: 0.1
